backend:
  name: github
  repo: bthuerman/firstlutheranogdensburg
  branch: main
  squash_merges: true
  auth_scope: "repo"
  auth_type: "implicit"
  client_id: "Ov23li5oY7OMdM6mbUeN"
  client_secret: "f75eafc97fba5efa5fb79df40f73e1d3ed0bf67b"

media_folder: "static/media"  # Folder for uploaded images (adjust if you want)
public_folder: "/media"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
