backend:
  name: github
  repo: bthuerman/firstlutheranogdensburg
  branch: main
  auth_type: implicit
  client_id: Ov23li5oY7OMdM6mbUeN

media_folder: "static/media"
public_folder: "/static/media"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
