backend:
  name: git-gateway
  branch: main

media_folder: "static/media"
public_folder: "/static/media"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/home.md"
        label: "Home Page"
        name: "home"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"
