backend:
  name: git-gateway
  branch: main

media_folder: "src/media"
public_folder: "/media"

editor:
  preview: false

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/pages/giving.md"
        label: "Giving Page"
        name: "giving"
        slug: "giving"
        format: "frontmatter"
        preview_path: "giving"
        fields:
          - { label: "Page (Tab) Title", name: "title", widget: "string" }

          - { label: "Banner Title", name: "banner_title", widget: "string" }

          - { label: "Giving Image", name: "giving_image", widget: "image" }

          - { label: "Giving Heading", name: "giving_heading", widget: "string" }
          - { label: "Giving Paragraph", name: "giving_paragraph", widget: "text" }
          - { label: "Button Link", name: "giving_button_link", widget: "string" }
          - { label: "Button Text", name: "giving_button_text", widget: "string" }
