backend:
  name: git-gateway
  branch: main

media_folder: "src/media"
public_folder: "/media"

editor:
  preview: false

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/pages/giving.md"
        label: "Giving Page"
        name: "giving"
        slug: "giving"
        format: "frontmatter"
        preview_path: "giving"
        fields:
          - { label: "Page (Tab) Title", name: "giving_title", widget: "string" }

          - { label: "Banner Title", name: "giving_banner_title", widget: "string" }

          - { label: "Image", name: "giving_image", widget: "image" }

          - { label: "Heading", name: "giving_heading", widget: "string" }
          - { label: "Paragraph", name: "giving_paragraph", widget: "text" }
          - { label: "Button Link", name: "giving_button_link", widget: "string" }
          - { label: "Button Text", name: "giving_button_text", widget: "string" }

      - file: "src/content/pages/contact.md"
        label: "Contact Page"
        name: "contact"
        slug: "contact"
        format: "frontmatter"
        preview_path: "contact"
        fields:
          - { label: "Page (Tab) Title", name: "contact_title", widget: "string" }

          - { label: "Banner Title", name: "contact_banner_title", widget: "string" }

          - { label: "Heading Line 1", name: "contact_heading_line_1", widget: "string" }    
          - { label: "Heading Line 2", name: "contact_heading_line_2", widget: "string" }                   

          - { label: "Address Text", name: "contact_address_text", widget: "string" }
          - { label: "Address Link", name: "contact_address_link", widget: "string" }
          - { label: "Phone Text", name: "contact_phone_text", widget: "string" }
          - { label: "Phone Link", name: "contact_phone_link", widget: "string" }
          - { label: "Email Text", name: "contact_email_text", widget: "string" }
          - { label: "Email Link", name: "contact_email_link", widget: "string" }

          - { label: "Google Maps Embed Link", name: "google_maps_embed_link", widget: "text" }
